services:
  backend:
    image: sing2eng.cs-gdg.osu/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app
    environment:
      - MODE=development
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
